
name: Terraform CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Security Scan, Plan and Apply
    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # 1. Checkout Repository
      # ==========================================
      - name: Checkout
        uses: actions/checkout@v4

      # ==========================================
      # 2. Setup Terraform
      # ==========================================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # ==========================================
      # 3. Terraform Version
      # ==========================================
      - name: Terraform Version
        run: terraform version

      # ==========================================
      # 4. Azure Login using Client Secret
      # ==========================================
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ==========================================
      # 5. Check Azure Account
      # ==========================================
      - name: Azure Account
        run: az account show

      # ==========================================
      # 6. Setup TFLint
      # ==========================================
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      # ==========================================
      # 7. TFLint Scan
      # ==========================================
      - name: Run TFLint
        run: |
          tflint --init
          tflint

      # ==========================================
      # 8. tfsec Security Scan
      # ==========================================
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: .
          soft_fail: false

      # ==========================================
      # 9. Terraform Init
      # ==========================================
      - name: Terraform Init
        run: terraform init

      # ==========================================
      # 10. Terraform Validate
      # ==========================================
      - name: Terraform Validate
        run: terraform validate

      # ==========================================
      # 11. Terraform Plan
      # ==========================================
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # ==========================================
      # 12. Terraform Apply
      # ==========================================
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan